server {
    listen 80;
    listen [::]:80;

    server_name economy.riversoft.top;

    root /var/www/economy;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|mjs|map|jpg|jpeg|png|gif|svg|webp|ico|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";
        try_files $uri =404;
    }
}
